# Generated by Django 2.0 on 2017-12-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_artist',
            new_name='album_title',
        ),
    ]
